### PR TITLE
add portuguese

### PR DESCRIPTION
**Pull request by Psykozis**
-add portuguese language to the js files

### CODE REVIEW

**Comment by Psykozis** [comment]
I am grateful to the person who translated into Spanish.
This edition to support Portuguese was only possible thanks to comparisons with her translation.

**Comment by Psykozis** [comment]
I tested this online, the portuguese language looks good, but the result page (for portuguese or english) don't show the botton image or the text results, only shows the percentual values... I sugest revert the changes, I will see this better at night...
Health n' freedom

**Comment by maoanran** [comment]
The problem is the last dot
https://github.com/LeftValues/leftvalues.github.io/pull/46/files#diff-0294a8f4f2c5110aa73f4d8973410134R75
```
"O marxismo ortodoxo é uma forma de marxismo que adota visões que se adequam à teoria marxista como foi originalmente escrita, particularmente sobre o materialismo dialético. Os marxistas ortodoxos são altamente revolucionários e internacionalistas e argumentam que sociedades não industriais são incapazes de alcançar o socialismo ".
```

**Comment by maoanran** [comment]
One more place need to be fixed.
https://github.com/LeftValues/leftvalues.github.io/pull/46/files#diff-0294a8f4f2c5110aa73f4d8973410134R291

**Comment by Psykozis** [comment]
thanx! I did this!

**Comment by maoanran** [comment]
No problem, there is an another one.
https://github.com/LeftValues/leftvalues.github.io/pull/46/files#diff-0294a8f4f2c5110aa73f4d8973410134R334

**Comment by ZerataX** [comment]
sorry about that

**Comment by Psykozis** [comment]
sorry, but it is already solved.
conrade @maoanran help a lot!

**Pull request merged**
