### PR TITLE
added i18n + german translation

### PR DESCRIPTION
**Pull request by ZerataX**
so I tried to create a small system to quickly add translations that will default to the english original lines and added a german translation as example.
translation will be picked by language of the browser UI.

I hope this is what #1 had in mind

Now to add a translation only edit these files
  - `ideologies.js`
  - `questions.js`
  - `i18n.js`

The translations are kept in a simple dict that also allows for functions, e.g.:
```javascript
"quiz-strongly-agree": {
  "en": "Strongly agree",
  "de": "Stimme voll zu"        
},
"quiz-question-of": {
  en(qn, questions) {return `Question ${qn + 1} of ${questions.length}`},
  de(qn, questions) {return `Frage ${qn +1} von ${questions.length}`}
},
```

Here are two browsers with different UI languages set:
two browser with different languages

it's live at https://zeratax.github.io/leftvalues.github.io/

### CODE REVIEW

**Comment by LeftValues** [comment]
It looks good, however perhaps it would be better to switch to the translation through a button (similar to the French translation) rather than it being automatic, as some browsers may not work with that.

**Comment by ZerataX** [comment]
okay added a simple selection tag
lang selection

**Comment by ZerataX** [comment]
if @mrtino is interested I can port his translations over to this system as well. I think this should be slightly nicer since stuff like the effects and status don't have to be changed for every language and the page should always be uptodate even the translation is slightly behind

**Comment by LeftValues** [comment]
@ZerataX 
It looks like the question about trade unionism was not translated. I am adding a translation done through Google as a temporary fix to prevent the quiz from bugging out. I've requested to add you as a collaborator if you wish to fix that directly.

**Comment by mrtino** [comment]
It would be great if you could port my work to your system, I don't really have time to do this currently. I'll translate the new questions as soon as possible.

**Pull request merged**
