### PR TITLE
[WIP] Add French Translation

### PR DESCRIPTION
**Pull request by mrtino**
I added a button to change between English and French, which should lead the way to other translations. To avoid creating multiple folders and thus duplicating files, I just created .fr.html and .fr.js files, so it would still depend on "static" files such as CSS files and images.

### CODE REVIEW

**Comment by LeftValues** [comment]
Looks great! I will merge once the recent few additions have been translated.

**Comment by ZerataX** [comment]
- missing
    - `questions.js`
      - The means of production, such as factories and farms, must be publicly owned.
      - Any socialist country should be dedicated to exporting their ideology abroad.
      - Humanity must return to the primitive ways of the past to overcome long-term climate issues.
      - Prisons are oppressive and antiquated institutions that need to be abolished.
      - Mass foreign immigration policies are naïve and should not be implemented.
      - ''From each according to his ability, to each according to his needs'' is a good principle.
      - A highly centralized planned economy is not socialism but rather state capitalism.
      - It is necessary to establish a dictatorship of the proletariat as a transitionary stage between
 capitalism and socialism.
      - Trade unionism has been largely corrupted by the ruling class and is no longer a viable structure for a socialist organization.
  - probably not uptodate
    - `i18n.js`
      - index-p-scores
      - result-issues
    - `ideologies.js`
      - Marxism-Leninism desc
    - `questions.js`
      - Marriage is a patriarchal social construct that should be phased out.
      - Religions overall have a mostly positive effect and should remain influential in society.
      - A socialist government has no right to disrupt religious or cultural traditions in any situation.
      - Only a mass workers party can achieve any meaningful long-term goals.

**Comment by ZerataX** [comment]
Okay fixed the merge conflicts and added 
```js
// TODO:
```
To all the missing translations so they're easily searchable

**Comment by kwrothchild** [comment]
We don't code, but my partner is a native French speaker and I am a native English speaker. We would like to help with the French translation. If you can tell us what still needs to be translated, we can help complete it. Cheers! 
K & T

**Comment by ZerataX** [comment]
@kwrothchild wow that sounds awesome. I left `// TODO:` everywhere a french translation is still missing so you just need to add search for that in these files:
 - https://github.com/mrtino/leftvalues.github.io/blob/french-translation/ideologies.js
 - https://github.com/mrtino/leftvalues.github.io/blob/french-translation/questions.js
 - https://github.com/mrtino/leftvalues.github.io/blob/french-translation/i18n.js

I hope you can just edit these files with the webinterface, I'm not super well versed with the github permission system.

If anything doesn't work that's no problem you can always ask or I'll just fix it myself ^^

**Comment by kwrothchild** [comment]
@ZerataX , Thanks so much! We have two questions:
1) For things that are not questions (i.e.) descriptions of the ideologies, is there somewhere where we can see what has been written in English so we can translate your working definition rather than writing a new definition ?
2) When clicking on the links to edit, it says that a "fork" is being created so the proposed changes will go to review. Is that correct/what we should be doing?
Sorry if these are silly questions -- we are not coders! Just passionate about politics and language :)
K&T

**Comment by ZerataX** [comment]
@kwrothchild hey I just spend the night making this process a lot more straightforward (hopefully ^^)
it's not yet actually in use, but I'm fairly sure it will be and you should definitely be able to already create translations with it, even if they won't immediately show up on the finished website until I hear back from the project owner.

I host this website here https://l10n.dmnd.sh/projects/leftvalues/leftvalues/fr/ which should have a very easy to understand interface where you can also always see the original english definition.

**Comment by ZerataX** [comment]
so since the weblate branch is merged this is also merged and can be closed, even if the french translation is not yet done

**Comment by kwrothchild** [comment]
Thanks @ZerataX ! Much appreciated ! We are trying to coordinate a time to sit down together and work on this within the next week :)

**Comment by kwrothchild** [comment]
Hi @ZerataX , Sorry that we are slow. We went back to continue, and seems like there is a problem with https://l10n.dmnd.sh/projects/leftvalues/leftvalues/fr/ now -- when we click we get an error message.

**Comment by ZerataX** [comment]
@kwrothchild sorry was doing some maintenance should be back up again

**Comment by ZerataX** [comment]
@kwrothchild sorry was doing some maintenance should be back up again

**Pull request closed without merging**
