### PR TITLE
better backbutton

### LINKED ISSUE #13: Can only go back one question
Is it intentional that you can only go back to the previous question? People should be able to go back all of the way and buttons to Reset the Quiz and to go Back to the Home Page should probably be available throughout the quiz.

I was thinking of contributing to the project by making it accessible to users with disabilities, most specifically those who use screen readers, but enhancements like the above are also very helpful for all users. 

Let me know if you'd like some help! Thanks for the quiz - it was fun

### PR DESCRIPTION
**Pull request by ZerataX**
!closes #13 
Everything gets saved into a cookie that looks like this:
cookie
and expires after 1 hour.
switching between languages or reloading now also won't reset your currently entered questions.
After answering the last question or waiting one hour everything should be reset again.

it should also now be fairly easy to instead of decrementing or incrementing to do #6 

**I don't have tested this much**

### CODE REVIEW

**Comment by sparkz9502** [comment]
So I tested it locally and it seemed to work fine, but once merged into master it seems to not work properly on the web. For now I've reverted the merge.

**Comment by ZerataX** [comment]
hmm not worked properly as in?

**Comment by ZerataX** [comment]
tried it on a fork and seems to work fine, did take like a few minutes to update tho
https://zeratax.github.io/leftvalues.github.io/quiz.html

**Comment by sparkz9502** [comment]
@ZerataX In my experience (using Google Chrome), the results error out, with all displaying as 50%. Additionally, it seems it is not possible to go back to the first question after getting to the second question.

**Comment by ZerataX** [comment]
oh yeah same for me with firefox, I'll look at that tomorrow. was that the same when you merged it to master?

**Comment by sparkz9502** [comment]
Yeah, the same issues occurred.

**Pull request merged**
